name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Verify SSH connection
        run: |
          ssh -o ConnectTimeout=10 -o BatchMode=yes ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} 'echo "SSH connection successful"'

      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=yes -o ConnectTimeout=30 ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
            set -e
            echo "Starting deployment at $(date)"
            if [ -f /home/azureuser/startup.sh ]; then
              chmod +x /home/azureuser/startup.sh
              sh /home/azureuser/startup.sh
              echo "Deployment completed successfully at $(date)"
            else
              echo "Error: startup.sh not found"
              exit 1
            fi
          EOF
